apiVersion: v1
kind: Service
metadata:
  labels:
    run: web
  name: web
  namespace: test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: web
  sessionAffinity: None
  type: ClusterIP
